# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 193e6ad8e67dd4cdbd74d42de953a5d2f951850793dd2d5e33dc1198dbb72f4bd0e2aa3e309d9421d40f52163d9e6cb00e63ab6fcf64fcecd95ae5d5798a2fef

test:
  secret_key_base: f3dcfb3834778c3c75fe6e69cfe9c22226b1fd9efb72d4b0204718ef3a59e1446f94bae2ed58e993ba7de746183f7da51a8871fdce9941cfce10b476f50f8924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
