# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f4a5f73f9da4a2ece43dcc9b9d92b26a75c791d23ba786bc6916008a9fd3e9bc2d63862a67b4eba371c588c3dd901c1ac6d9f147d51a832f90064103c19b69

test:
  secret_key_base: 796c6462546dc87ec60f6e77564578960fdc10c2a676bd1b38f79c3ac3355c846c6cc96f514dc196ab2799c003e1adf7701f5a5697f865a68a9dfe7eea45485a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
